// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/21/2024, 9:05:36 AM
const configMerger = require("/Users/minh/Developer/REWORKFLOW/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/minh/Developer/REWORKFLOW/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/minh/Developer/REWORKFLOW/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/minh/Developer/REWORKFLOW/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/minh/Developer/REWORKFLOW/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/minh/Developer/REWORKFLOW/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/minh/Developer/REWORKFLOW/plugins/**/*.{js,ts,mjs}","/Users/minh/Developer/REWORKFLOW/composables/**/*.{js,ts,mjs}","/Users/minh/Developer/REWORKFLOW/utils/**/*.{js,ts,mjs}","/Users/minh/Developer/REWORKFLOW/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/minh/Developer/REWORKFLOW/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/minh/Developer/REWORKFLOW/app.config.{js,ts,mjs}"] }));

module.exports = config
